<!DOCTYPE html>
<html>
    <head>
        <title>Gunblues</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta property="og:title" content="Gunblues"/>
        <meta property="og:type" content="website" />
        <meta property="og:url" content="http://www.gunblues.com" />
        <meta property="og:image" content=""/>
        <meta property="og:image:secure_url" content="" />
        <meta property="og:site_name" content="Gunblues"/>
        <meta property="og:description" content="<?php echo HTML_DESCRIPTION; ?>"/>
        <meta name="google-site-verification" content="wI2geJcmG0EQ5IYlotDeJykhrUglaoPNK1HkpaObzy8">
        <meta name="msvalidate.01" content="B6F05BD0BE44FCADBC7A865961F33AF0">
        <meta name="alexaVerifyID" content="Km_EvG1ziHd12yLDO20fFrvSRpI" />
        <meta name="keywords" content="<?php echo HTML_KEYWORDS; ?>">
        <meta name="description" content="<?php echo HTML_DESCRIPTION; ?>">
        <link rel="canonical" href="http://www.gunblues.com" />
        <link rel="shortcut icon" href="/assets/images/favicon.ico">
        <link href="//code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.css" rel="stylesheet" type="text/css" />
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="//oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <script src="//code.jquery.com/jquery-1.7.1.min.js"></script>
        <script src="//code.jquery.com/mobile/latest/jquery.mobile.min.js"></script>
    </head>
    <body>
        <div data-role="page" data-theme="d" id="mypage" data-ajax="false">
            <div data-role="header">
                 <h1><?php echo SITE_NAME; ?></h1>
            </div>
            <div data-role="content">
                <ul data-role="listview" data-inset="false" data-filter="false">
                    <li>
                        <a rel="external" href="http://film.gunblues.com<?php echo $para; ?>">
                            <img src="/assets/images/youtubeg72x72.png"/>
                            <h3><?php echo URFILM; ?></h3>
                            <p><em><?php echo URFILM_DESC; ?></em></p>
                        </a>
                    </li>
                    <li>
                        <a rel="external" href="http://www.myyasui.com<?php echo $para; ?>">
                            <img src="/assets/images/myyasui72x72.png"/>
                            <h3><?php echo MYYASUI; ?></h3>
                            <p><em><?php echo MYYASUI_DESC; ?></em></p>
                        </a>
                    </li>
                    <li>
                        <a rel="external" href="<?php echo $stock . $para; ?>">
                            <img src="/assets/images/myokane72x72.png"/>
                            <h3><?php echo TWSTOCK; ?></h3>
                            <p><em><?php echo TWSTOCK_DESC; ?></em></p>
                        </a>
                    </li>
                    <li>
                        <a rel="external" href="http://langja.com<?php echo $para; ?>">
                            <img src="/assets/images/musicg72x72.png"/>
                            <h3><?php echo URMUISC; ?></h3>
                            <p><em><?php echo URMUISC_DESC; ?></em></p>
                        </a>
                    </li>
<!--
                    <li>
                        <a rel="external" href="http://ilovepopcorn.club/">
                            <img src="/assets/images/ilovepopcorn72x72.png"/>
                            <h3><?php echo ILOVEPOPCORN; ?></h3>
                            <p><em><?php echo ILOVEPOPCORN_DESC; ?></em></p>
                        </a>
                    </li>
-->
               </ul>
            </div>
        </div>
        <script type="text/javascript">
        
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-31833010-1']);
          _gaq.push(['_trackPageview']);
        
          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        
        </script>
    </body>
</html>
