<!DOCTYPE html>
<html>
    <head>
        <title>Gunblues</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta property="og:title" content="Gunblues"/>
        <meta property="og:type" content="website" />
        <meta property="og:url" content="http://www.gunblues.com" />
        <meta property="og:image" content=""/>
        <meta property="og:image:secure_url" content="" />
        <meta property="og:site_name" content="Gunblues"/>
        <meta property="og:description" content="<?php echo HTML_DESCRIPTION; ?>"/>
        <meta name="google-site-verification" content="wI2geJcmG0EQ5IYlotDeJykhrUglaoPNK1HkpaObzy8">
        <meta name="msvalidate.01" content="B6F05BD0BE44FCADBC7A865961F33AF0">
        <meta name="alexaVerifyID" content="Km_EvG1ziHd12yLDO20fFrvSRpI" />
        <meta name="keywords" content="<?php echo HTML_KEYWORDS; ?>">
        <meta name="description" content="<?php echo HTML_DESCRIPTION; ?>">
        <link rel="canonical" href="http://www.gunblues.com" />
        <link rel="shortcut icon" href="/assets/images/favicon.ico">
        <link href="//code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.css" rel="stylesheet" type="text/css" />
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="//oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <script src="//code.jquery.com/jquery-1.7.1.min.js"></script>
        <script src="//code.jquery.com/mobile/latest/jquery.mobile.min.js"></script>
    </head>
    <body>
        <div data-role="page" data-theme="d" id="mypage" data-ajax="false">
            <div data-role="header">
                 <h1><?php echo PRIVACY_POLICY; ?></h1>
            </div>
            <div data-role="content">
<pre>
本開發者gunblues於Google Play上提供之所有應用程式，均符合以下隱私權政策規範:

當您使用APP功能時，我們將視該服務功能性質，請您提供必要的APP系統權限，並在該特定目的範圍內處理及利用您的個人資料；本APP不會將個人資料用於其他用途。本人不會於任何伺服器會自行記錄相關行徑，包括您使用連線設備的IP位址、使用時間、使用的瀏覽器、瀏覽及點選資料記錄等。
本APP其他第三方APP的網路連結，不適用本網站的隱私權保護政策，您必須參考該連結網站中的隱私權保護政策。
本APP絕不會提供、交換、出租或出售任何您的個人資料給其他個人、團體、私人企業或公務機關。
本網站隱私權保護政策將因應需求隨時進行修正，修正後的條款將刊登於網站上。

All apps provided by this developer, suc1982, on Google Play are subject to the following privacy policy:

When you use the APP function, we will regard the nature of the service function, you provide the necessary APP system permissions, and within the scope of the specific purpose of handling and use of your personal information; this APP will not use personal data for other purposes . I will not automatically record any action on any server, including the IP address of the device you are using, the time of use, the browser you are using, browsing, and clicking on data records.
This APP's other third party APP's web link does not apply to the privacy policy of this site, you must refer to the privacy policy in the link site.

The APP will never provide, exchange, rent or sell any of your personal information to other individuals, groups, private enterprises or public authorities.

The privacy policy of this site will be amended at any time in accordance with the needs, the revised terms will be published on the website.
</pre>
            </div>
        </div>
        <script type="text/javascript">
        
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-31833010-1']);
          _gaq.push(['_trackPageview']);
        
          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        
        </script>
    </body>
</html>
