#!/bin/bash
 
# Don't forget the trailing / on the source directory - if you omit it,
# it will copy the directory over, rather than just its contents.
# NOTE: no trailing slash on destination directory

export DEPLOY_SOURCE_DIR=
export DEPLOY_DEST_DIR=
export DEPLOY_SERVER=
export DEPLOY_ACCOUNT=
export DEPLOY_KEY=

export WWW_RIGHTFUL_OWNER=
