#!/bin/bash
 
# Don't forget the trailing / on the source directory - if you omit it,
# it will copy the directory over, rather than just its contents.
# NOTE: no trailing slash on destination directory

export DEPLOY_SOURCE_DIR=./app/
export DEPLOY_DEST_DIR=/var/www/gunblues
export DEPLOY_SERVER=172.104.64.171
export DEPLOY_ACCOUNT=kevin
export DEPLOY_KEY=

export WWW_RIGHTFUL_OWNER=www-data
