#!/bin/bash
 
# Set the environment by loading from the file "environment" in the same directory
DIR="$( cd "$( dirname "$0" )" && pwd)"
source $DIR/environment

# Provide credentials.
while true; do
    read -p "==> WHO ARE YOU? " DEPLOY_ACCOUNT
    case $DEPLOY_ACCOUNT in
        "" )
            echo -e "\e[00;31mTELL ME WHO YOU ARE\e[00m"
            ;;

        * )
            DEPLOY_ACCOUNT=$(echo "$DEPLOY_ACCOUNT" | tr  -d "[:space:]")
            break;;
    esac
done

echo -e "\e[00;33mDeploying as    \e[00;31m$DEPLOY_ACCOUNT\e[00m\e[00m"
echo -e "\e[00;33mDeploying from  \e[00;31m$DEPLOY_SOURCE_DIR\e[00m\e[00m"
echo -e "\e[00;33mDeploying to    \e[00;31m$DEPLOY_SERVER:$DEPLOY_DEST_DIR\e[00m\e[00m"
echo -e

# Assets minification.
while true; do
    read -p "==> Minimize CSS and JavaScript? (Y/N) "
    case $REPLY in
        [Yy] )
            if ! grunt_path="$(type -p "grunt")" || [ -z "$grunt_path" ]; then
                echo -e "\e[00;31mGrunt not found. Skipping minification...\e[00m"
            else
                echo -e "\e[00;33mMinifying...\e[00m"
                grunt
            fi

            break;;

        [Nn] )
            echo -e "\e[00;31mSkipping minification...\e[00m"
            break;;

        * )
            echo -e "\e[00;31mPlease type Y or N\e[00m"
    esac
done

# Deploy with rsync.
echo -e 
while true; do
    read -p "==> Does this look good? Can I go ahead and deploy ? (Y/N) " 
    case $REPLY in
        [Yy] )
            # Change entire owner/group to deploy account in order to have the proper permissions.
            echo -e "\e[00;33mChanging directory permission to $DEPLOY_ACCOUNT:$DEPLOY_ACCOUNT...\e[00m"
            ssh -p 16888 -t $DEPLOY_ACCOUNT@$DEPLOY_SERVER "sudo chown -R $DEPLOY_ACCOUNT:$DEPLOY_ACCOUNT $DEPLOY_DEST_DIR"

            echo -e "\e[00;33mBegin rsync...\e[00m"
            if [ "$DEPLOY_KEY" == "" ]; then
                # Access by tediously typing a password over and again
                rsync --chmod=ug=rwX --rsh='ssh -p16888' -axv --delete --exclude-from=$DIR/rsync-exclude \
                    $DEPLOY_SOURCE_DIR $DEPLOY_ACCOUNT@$DEPLOY_SERVER:$DEPLOY_DEST_DIR
            else
                # Access by key
                rsync --chmod=ug=rwX --rsh='ssh -p16888' -axv --delete --exclude-from=$DIR/rsync-exclude \
                    -e ssh -i $DEPLOY_KEY $DEPLOY_SOURCE_DIR $DEPLOY_ACCOUNT@$DEPLOY_SERVER:$DEPLOY_DEST_DIR
            fi

            # Change back permissions.
            echo -e "\e[00;33mChanging directory permission back to $WWW_RIGHTFUL_OWNER:$WWW_RIGHTFUL_OWNER...\e[00m"
            ssh -p 16888 -t $DEPLOY_ACCOUNT@$DEPLOY_SERVER "sudo chown -R $WWW_RIGHTFUL_OWNER:$WWW_RIGHTFUL_OWNER $DEPLOY_DEST_DIR"
            
            break;;

        [Nn] )
            echo -e "\e[00;31mSkipping deploy...\e[00m"
            break;;

        * )
            echo -e "\e[00;31mPlease type Y or N\e[00m"
    esac
done

# Saying good-bye.
echo -e
echo -e "\e[00;31mDeploy complete, you're responsible now.\e[00m"
exit 1
